//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionElectronica.Homologacion {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FacturacionElectronica.Homologacion.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .zip.
        /// </summary>
        internal static string ExtensionFile {
            get {
                return ResourceManager.GetString("ExtensionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Errors&gt;
        ///  &lt;Error code=&quot;100&quot;&gt;
        ///    &lt;value&gt;El sistema no puede responder su solicitud. Intente nuevamente o comuníquese con su Administrador &lt;/value&gt;
        ///  &lt;/Error&gt;
        ///  &lt;Error code=&quot;101&quot;&gt;
        ///    &lt;value&gt;El encabezado de seguridad es incorrecto &lt;/value&gt;
        ///  &lt;/Error&gt;
        ///  &lt;Error code=&quot;102&quot;&gt;
        ///    &lt;value&gt;Usuario o contraseña incorrectos &lt;/value&gt;
        ///  &lt;/Error&gt;
        ///  &lt;Error code=&quot;103&quot;&gt;
        ///    &lt;value&gt;El Usuario ingresado no existe &lt;/value&gt;
        ///  &lt;/Error&gt;
        ///  &lt;Error code=&quot;104&quot;&gt;
        ///    &lt;value&gt;La Cla [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ListadeErrores {
            get {
                return ResourceManager.GetString("ListadeErrores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://e-beta.sunat.gob.pe/ol-ti-itcpfegem-beta/billService.
        /// </summary>
        internal static string UrlBeta {
            get {
                return ResourceManager.GetString("UrlBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://e-guiaremision.sunat.gob.pe/ol-ti-itemision-guia-gem/billService.
        /// </summary>
        internal static string UrlGuia {
            get {
                return ResourceManager.GetString("UrlGuia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://e-beta.sunat.gob.pe/ol-ti-itemision-guia-gem-beta/billService.
        /// </summary>
        internal static string UrlGuiaBeta {
            get {
                return ResourceManager.GetString("UrlGuiaBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://www.sunat.gob.pe/ol-ti-itcpgem-sqa/billService.
        /// </summary>
        internal static string UrlHomologacion {
            get {
                return ResourceManager.GetString("UrlHomologacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://www.sunat.gob.pe/ol-ti-itcpgem-beta/billService.
        /// </summary>
        internal static string UrlHomologacionBeta {
            get {
                return ResourceManager.GetString("UrlHomologacionBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://e-factura.sunat.gob.pe/ol-ti-itcpfegem/billService.
        /// </summary>
        internal static string UrlProduccion {
            get {
                return ResourceManager.GetString("UrlProduccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://www.sunat.gob.pe/ol-ti-itemision-otroscpe-gem/billService.
        /// </summary>
        internal static string UrlRetPerc {
            get {
                return ResourceManager.GetString("UrlRetPerc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://e-beta.sunat.gob.pe/ol-ti-itemision-otroscpe-gem-beta/billService.
        /// </summary>
        internal static string UrlRetPercBeta {
            get {
                return ResourceManager.GetString("UrlRetPercBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://www.sunat.gob.pe:443/ol-it-wsconscpegem/billConsultService.
        /// </summary>
        internal static string UrlServiceConsult {
            get {
                return ResourceManager.GetString("UrlServiceConsult", resourceCulture);
            }
        }
    }
}
