//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionElectronica.Homologacion {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://e-beta.sunat.gob.pe/ol-ti-itcpfegem-beta/billService")]
        public string UrlServiceSunat {
            get {
                return ((string)(this["UrlServiceSunat"]));
            }
            set {
                this["UrlServiceSunat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Beta")]
        public global::FacturacionElectronica.Homologacion.Res.ServiceSunatType ServiceCurrent {
            get {
                return ((global::FacturacionElectronica.Homologacion.Res.ServiceSunatType)(this["ServiceCurrent"]));
            }
            set {
                this["ServiceCurrent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://e-beta.sunat.gob.pe/ol-ti-itemision-guia-gem-beta/billService")]
        public string UrlServiceGuia {
            get {
                return ((string)(this["UrlServiceGuia"]));
            }
            set {
                this["UrlServiceGuia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://e-beta.sunat.gob.pe/ol-ti-itemision-otroscpe-gem-beta/billService")]
        public string UrlRetPerc {
            get {
                return ((string)(this["UrlRetPerc"]));
            }
            set {
                this["UrlRetPerc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Beta")]
        public global::FacturacionElectronica.Homologacion.Res.ServiceSunatType ServiceRetPer {
            get {
                return ((global::FacturacionElectronica.Homologacion.Res.ServiceSunatType)(this["ServiceRetPer"]));
            }
            set {
                this["ServiceRetPer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Beta")]
        public global::FacturacionElectronica.Homologacion.Res.ServiceSunatType ServiceGuia {
            get {
                return ((global::FacturacionElectronica.Homologacion.Res.ServiceSunatType)(this["ServiceGuia"]));
            }
            set {
                this["ServiceGuia"] = value;
            }
        }
    }
}
